name: Build & Deploy

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Install npm, test and run build
        run: |		
          npm install
          npm test
          npm run build
          
      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: privtap-bucket
          bucket-region: eu-central-1