name: Test

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  deploy:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install npm and test
        run: |		
          npm install
          npm test